#!/bin/sh

# Overwrite network configuration with default settings
cat > /etc/config/network << 'EOF'
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd17:4a2a:e040::/48'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth0'

config interface 'lan'
	option device 'eth0'
	option proto 'dhcp'
	option ipaddr '192.168.1.100'
	option netmask '255.255.255.0'
	option ip6assign '60'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '0'
EOF

# Set interface to extract MAC address
IFACE="eth0"
PREFIX="wallcontroller"

# Get MAC address
mac=$(ifconfig "$IFACE" | grep -o -E '([[:xdigit:]]{2}:){5}[[:xdigit:]]{2}' | head -n1)
if [ -n "$mac" ]; then
    last4=$(echo "$mac" | tr -d ':' | tail -c 5)
    newname="${PREFIX}-${last4}"

    # Set hostname
    uci set system.@system[0].hostname="$newname"
    echo "$newname" > /etc/hostname
    sed -i "s/127.0.1.1.*/127.0.1.1\t$newname/" /etc/hosts
fi

# Set timezone to CET
uci set system.@system[0].timezone='CET-1CEST,M3.5.0,M10.5.0/3'
uci set system.@system[0].zonename='Europe/Berlin'

# Disable all radios
for section in $(uci show wireless | grep "=wifi-device" | cut -d. -f2 | cut -d= -f1); do
    uci set wireless.$section.disabled='1'
done

# Commit changes
uci commit system
uci commit wireless
uci commit network

# Reload affected services
/etc/init.d/system reload
wifi reload
/etc/init.d/network reload

exit 0
